name: Hexo Deploy


# active when 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy file to github action
      uses: actions/checkout@v2

    - name: Setup Node.js environemnt
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install

    - name: Build static html
      run: npm run build
      
    - name: publish and push
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    
